version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage:
    name: compile
    displayName: 编译
    steps:
      - step: build@gradle
        name: build_gradle
        displayName: Gradle 构建
        jdkVersion: 17
        gradleVersion: 8.2
        commands:
          - chmod +x ./gradlew
          - ./gradlew assembleDebug
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./app/build/outputs/apk
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_gradle
triggers:
  pr:
    branches:
      include:
        - master
